language: node_js
node_js:
  - 6
script: yarn start

git:
  depth: 1000

# Deploy to server after successfull run
after_success:
  - ./deploy.sh

# Enable yarn cache
cache: yarn

# Only build master branch
branches:
  only:
    - master

# Add www.timroes.de to known hosts
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev
