language: node_js
node_js:
  - node
before_script:
  - npm install -g gulp
script: gulp build --production

git:
  depth: 1000

# Deploy to server after successfull run
after_success:
  - openssl aes-256-cbc -K $encrypted_a4b8f6cb10ef_key -iv $encrypted_a4b8f6cb10ef_iv -in deploy.key.enc -out deploy.key -d
  - chmod 600 deploy.key
  - ./deploy.sh
  - "curl -u $keycdn_api_key: https://api.keycdn.com/zones/purge/$keycdn_zone_id.json"

# Only build master branch
branches:
  only:
    - master
    - preview

# Add www.timroes.de to known hosts
addons:
  ssh_known_hosts: www.timroes.de
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev
