# The overall title of the blog
title: Tim Roes
# A headline for the blog
headline: computer scientist // android & web enthusiast
# The absolute base URL of the blog
url: https://www.timroes.de
# The theme color as used for theming meta tags
theme_color: '#222222'
# The id of the main author of this blog (must be a valid author id, i.e. the name of
# one file in the content/authors/ directory)
author: timroes
# The locale and the language of this page.
locale: en_US
language: en
# Generel blog category. Will be used as category if no post category is available.
category: Technology

# Name of the favicon relative to the content folder
favicon: favicon.png

# Set a social share image for the blog itself (when not at a post, or no post image available)
banner: /banners/blog-timroes.png

# The id of the GitHub repository, this blog is stored (will be used to generate links)
github_repo: timroes/www.timroes.de
